# Set update schedule for GitHub Actions
# See https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  labels:
    - type-infra
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: pub
  directory: /
  schedule:
    interval: monthly
  labels:
    - type-infra
