name: Install Dart
on:
  push:
    branches:
      - main
    paths:
      - '**.rb'
      - .github/workflows/install-dart.yml
  pull_request:
    paths:
      - '**.rb'
      - .github/workflows/install-dart.yml

permissions:
  contents: read

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@e99025eb970cfa124b8284a35463d87426917478

      - run: brew tap dart-lang/dart

      - run: brew trust dart-lang/dart

      - run: brew install dart
